import { CSSProperties } from 'react';

const flexCode = {
  start: 'flex-start',
  end: 'flex-end',
  between: 'space-between',
  around: 'space-around',
};
export const commonMatchs = [
  ['dis=', (v: any) => `{ display: ${v}; }`],
  ['flex-direction=', (v: any) => `{ display: flex; flex-direction: ${v}; }`],
  ['flex=', (v: any) => `{ flex-direction: ${v}; };`],
  ['items=', (v: any) => `{ align-items: ${(flexCode as any)[v] || v};}`],
  ['justify=', (v: any) => `{ justify-content: ${(flexCode as any)[v] || v}; }`],
  ['self=', (v: any) => `{ align-self: ${(flexCode as any)[v] || v} };`],
  ['content=', (v: any) => `{ align-content: ${(flexCode as any)[v] || v}; }`],
  ['flex=', (v: any) => `{ flex: ${v}; }`],
  ['flex-warp=', (v: any) => `{ flex-wrap: ${v}; }`],
  ['flex-grow=', (v: any) => `{ flex-grow: ${v}; }`],
  ['flex-shrink=', (v: any) => `{ flex-shrink: ${v} }`],
  ['pos=', (v: any) => `{ position: ${v}; }`],
  ['static.', (v: any) => `{ position: static; }`],
  ['absolute.', (v: any) => `{ position: absolute; }`],
  ['fixed.', (v: any) => `{ position: fixed; }`],
  ['relative.', (v: any) => `{ position: relative; }`],
  ['sticky.', (v: any) => `{ position: sticky; }`],
  ['z=', (v: any) => `{ z-index: ${v}; }`],
  // positions
  // ['left=', (v: any) => `{ left: ${v}; }`],
  // ['top=', (v: any) => `{ top: ${v}; }`],
  // ['right=', (v: any) => `{ right: ${v}; }`],
  // ['bottom=', (v: any) => `{ bottom: ${v}; }`],
  ['left.', (v: any) => `{ left: 0px; }`],
  ['top.', (v: any) => `{ top: 0px; }`],
  ['right.', (v: any) => `{ right: 0px; }`],
  ['bottom.', (v: any) => `{ bottom: 0px; }`],
  ['p=', (v: any) => `{ padding: ${v}; }`],
  ['px=', (v: any) => `{ padding: 0px ${v}; }`],
  ['py=', (v: any) => `{ padding: ${v} 0px; }`],
  ['pl=', (v: any) => `{ padding-left: ${v}; }`],
  ['pt=', (v: any) => `{ padding-top: ${v}; }`],
  ['pr=', (v: any) => `{ padding-right: ${v}; }`],
  ['pb=', (v: any) => `{ padding-bottom: ${v}; }`],
  ['m=', (v: any) => `{ margin: ${v}; }`],
  ['mx=', (v: any) => `{ margin: 0px ${v}; }`],
  ['my=', (v: any) => `{ margin: ${v} 0px; }`],
  ['ml=', (v: any) => `{ margin-left: ${v}; }`],
  ['mt=', (v: any) => `{ margin-top: ${v} };`],
  ['mr=', (v: any) => `{ margin-right: ${v}; }`],
  ['mb=', (v: any) => `{ margin-bottom: ${v}; }`],
  ['w=', (v: any) => `{ width: ${v} }`],
  ['minw=', (v: any) => `{ min-width: ${v}; }`],
  ['maxw=', (v: any) => `{ max-width: ${v}; }`],
  ['mmw=', (v: any) => `{ width: ${v}; max-width: ${v}; min-width: ${v}; }`],
  ['h=', (v: any) => `{ height: ${v}; }`],
  ['minh=', (v: any) => `{ min-height: ${v}; }`],
  ['maxh=', (v: any) => `{ maxHeight: ${v}; }`],
  ['mmh=', (v: any) => `{ height: ${v}; min-height: ${v}; max-width: ${v}; }`],
  ['b=', (v: any) => `{ border: ${v}; }`],
  ['bt=', (v: any) => `{ border-top: ${v}; }`],
  ['br=', (v: any) => `{ border-right: ${v}; }`],
  ['bb=', (v: any) => `{ border-bottom: ${v}; }`],
  ['bl=', (v: any) => `{ border-left: ${v}; }`],
  ['border=', (v: any) => `{ border: ${v} solid; }`],
  ['border-t=', (v: any) => `{ border-top: ${v} solid; }`],
  ['border-r=', (v: any) => `{ border-right: ${v} solid; }`],
  ['border-l=', (v: any) => `{ border-left: ${v} solid; }`],
  ['border-b=', (v: any) => `{ border-bottom: ${v} solid; }`],
  ['border-color=', (v: any) => `{ border-color: ${v}; }`],
  ['border-style=', (v: any) => `{ border-style: ${v}; }`],
  ['radius-t-l=', (v: any) => `{ border-top-left-radius: ${v}; }`],
  ['radius-t-r=', (v: any) => `{ border-top-right-radius: ${v}; }`],
  ['radius-b-l=', (v: any) => `{ border-bottom-left-radius: ${v}; }`],
  ['radius-b-r=', (v: any) => `{ border-bottom-right-radius: ${v}; }`],
  // theme
  ['bg=', (v: any) => `{ background: ${v}; }`],
  ['bgc=', (v: any) => `{ background-color: ${v}; }`],
  ['color=', (v: any) => `{ color: ${v}; }`],
  // events
  ['pointer-events=', (v: any) => `{ pointer-events: ${v}; }`],
  // block
  [
    'center.',
    (v: any) => `{
      display: flex;
      flex-direction: column;
      justify-content: flex-center;
      align-items: center;
    }`,
  ],
  ['row.', (v: any) => `{ display: flex; flex-direction: row; }`],
  ['row-reverse.', (v: any) => `{ display: flex; flex-direction: row-reverse; }`],
  ['col.', (v: any) => `{ display: flex; flex-direction: column; }`],
  ['col-reverse.', (v: any) => `{ display: flex; flex-direction: column-reverse; }`],
];
